/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.bmstu.users.manager.model;

import aQute.bnd.annotation.ProviderType;

import com.liferay.expando.kernel.model.ExpandoBridge;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;
import com.liferay.portal.kernel.model.WorkflowedModel;
import com.liferay.portal.kernel.service.ServiceContext;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the TraccarUser service. Represents a row in the &quot;UM_TraccarUser&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.bmstu.users.manager.model.impl.TraccarUserModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.bmstu.users.manager.model.impl.TraccarUserImpl}.
 * </p>
 *
 * @author Mosin
 * @see TraccarUser
 * @see com.bmstu.users.manager.model.impl.TraccarUserImpl
 * @see com.bmstu.users.manager.model.impl.TraccarUserModelImpl
 * @generated
 */
@ProviderType
public interface TraccarUserModel extends BaseModel<TraccarUser>, GroupedModel,
	ShardedModel, StagedAuditedModel, WorkflowedModel {
	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a traccar user model instance should use the {@link TraccarUser} interface instead.
	 */

	/**
	 * Returns the primary key of this traccar user.
	 *
	 * @return the primary key of this traccar user
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this traccar user.
	 *
	 * @param primaryKey the primary key of this traccar user
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this traccar user.
	 *
	 * @return the uuid of this traccar user
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this traccar user.
	 *
	 * @param uuid the uuid of this traccar user
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the traccar user ID of this traccar user.
	 *
	 * @return the traccar user ID of this traccar user
	 */
	public long getTraccarUserId();

	/**
	 * Sets the traccar user ID of this traccar user.
	 *
	 * @param traccarUserId the traccar user ID of this traccar user
	 */
	public void setTraccarUserId(long traccarUserId);

	/**
	 * Returns the traccar user uuid of this traccar user.
	 *
	 * @return the traccar user uuid of this traccar user
	 */
	public String getTraccarUserUuid();

	/**
	 * Sets the traccar user uuid of this traccar user.
	 *
	 * @param traccarUserUuid the traccar user uuid of this traccar user
	 */
	public void setTraccarUserUuid(String traccarUserUuid);

	/**
	 * Returns the group ID of this traccar user.
	 *
	 * @return the group ID of this traccar user
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this traccar user.
	 *
	 * @param groupId the group ID of this traccar user
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this traccar user.
	 *
	 * @return the company ID of this traccar user
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this traccar user.
	 *
	 * @param companyId the company ID of this traccar user
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this traccar user.
	 *
	 * @return the user ID of this traccar user
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this traccar user.
	 *
	 * @param userId the user ID of this traccar user
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this traccar user.
	 *
	 * @return the user uuid of this traccar user
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this traccar user.
	 *
	 * @param userUuid the user uuid of this traccar user
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this traccar user.
	 *
	 * @return the user name of this traccar user
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this traccar user.
	 *
	 * @param userName the user name of this traccar user
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this traccar user.
	 *
	 * @return the create date of this traccar user
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this traccar user.
	 *
	 * @param createDate the create date of this traccar user
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this traccar user.
	 *
	 * @return the modified date of this traccar user
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this traccar user.
	 *
	 * @param modifiedDate the modified date of this traccar user
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this traccar user.
	 *
	 * @return the status of this traccar user
	 */
	@Override
	public int getStatus();

	/**
	 * Sets the status of this traccar user.
	 *
	 * @param status the status of this traccar user
	 */
	@Override
	public void setStatus(int status);

	/**
	 * Returns the status by user ID of this traccar user.
	 *
	 * @return the status by user ID of this traccar user
	 */
	@Override
	public long getStatusByUserId();

	/**
	 * Sets the status by user ID of this traccar user.
	 *
	 * @param statusByUserId the status by user ID of this traccar user
	 */
	@Override
	public void setStatusByUserId(long statusByUserId);

	/**
	 * Returns the status by user uuid of this traccar user.
	 *
	 * @return the status by user uuid of this traccar user
	 */
	@Override
	public String getStatusByUserUuid();

	/**
	 * Sets the status by user uuid of this traccar user.
	 *
	 * @param statusByUserUuid the status by user uuid of this traccar user
	 */
	@Override
	public void setStatusByUserUuid(String statusByUserUuid);

	/**
	 * Returns the status by user name of this traccar user.
	 *
	 * @return the status by user name of this traccar user
	 */
	@AutoEscape
	@Override
	public String getStatusByUserName();

	/**
	 * Sets the status by user name of this traccar user.
	 *
	 * @param statusByUserName the status by user name of this traccar user
	 */
	@Override
	public void setStatusByUserName(String statusByUserName);

	/**
	 * Returns the status date of this traccar user.
	 *
	 * @return the status date of this traccar user
	 */
	@Override
	public Date getStatusDate();

	/**
	 * Sets the status date of this traccar user.
	 *
	 * @param statusDate the status date of this traccar user
	 */
	@Override
	public void setStatusDate(Date statusDate);

	/**
	 * Returns the name of this traccar user.
	 *
	 * @return the name of this traccar user
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this traccar user.
	 *
	 * @param name the name of this traccar user
	 */
	public void setName(String name);

	/**
	 * Returns the password of this traccar user.
	 *
	 * @return the password of this traccar user
	 */
	@AutoEscape
	public String getPassword();

	/**
	 * Sets the password of this traccar user.
	 *
	 * @param password the password of this traccar user
	 */
	public void setPassword(String password);

	/**
	 * Returns the email of this traccar user.
	 *
	 * @return the email of this traccar user
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this traccar user.
	 *
	 * @param email the email of this traccar user
	 */
	public void setEmail(String email);

	/**
	 * Returns <code>true</code> if this traccar user is approved.
	 *
	 * @return <code>true</code> if this traccar user is approved; <code>false</code> otherwise
	 */
	@Override
	public boolean isApproved();

	/**
	 * Returns <code>true</code> if this traccar user is denied.
	 *
	 * @return <code>true</code> if this traccar user is denied; <code>false</code> otherwise
	 */
	@Override
	public boolean isDenied();

	/**
	 * Returns <code>true</code> if this traccar user is a draft.
	 *
	 * @return <code>true</code> if this traccar user is a draft; <code>false</code> otherwise
	 */
	@Override
	public boolean isDraft();

	/**
	 * Returns <code>true</code> if this traccar user is expired.
	 *
	 * @return <code>true</code> if this traccar user is expired; <code>false</code> otherwise
	 */
	@Override
	public boolean isExpired();

	/**
	 * Returns <code>true</code> if this traccar user is inactive.
	 *
	 * @return <code>true</code> if this traccar user is inactive; <code>false</code> otherwise
	 */
	@Override
	public boolean isInactive();

	/**
	 * Returns <code>true</code> if this traccar user is incomplete.
	 *
	 * @return <code>true</code> if this traccar user is incomplete; <code>false</code> otherwise
	 */
	@Override
	public boolean isIncomplete();

	/**
	 * Returns <code>true</code> if this traccar user is pending.
	 *
	 * @return <code>true</code> if this traccar user is pending; <code>false</code> otherwise
	 */
	@Override
	public boolean isPending();

	/**
	 * Returns <code>true</code> if this traccar user is scheduled.
	 *
	 * @return <code>true</code> if this traccar user is scheduled; <code>false</code> otherwise
	 */
	@Override
	public boolean isScheduled();

	@Override
	public boolean isNew();

	@Override
	public void setNew(boolean n);

	@Override
	public boolean isCachedModel();

	@Override
	public void setCachedModel(boolean cachedModel);

	@Override
	public boolean isEscapedModel();

	@Override
	public Serializable getPrimaryKeyObj();

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj);

	@Override
	public ExpandoBridge getExpandoBridge();

	@Override
	public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

	@Override
	public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext);

	@Override
	public Object clone();

	@Override
	public int compareTo(TraccarUser traccarUser);

	@Override
	public int hashCode();

	@Override
	public CacheModel<TraccarUser> toCacheModel();

	@Override
	public TraccarUser toEscapedModel();

	@Override
	public TraccarUser toUnescapedModel();

	@Override
	public String toString();

	@Override
	public String toXmlString();
}